get_product_types:
  path: /product_types
  controller: App\Controller\ProductController::getProductTypes
  methods: GET

get_products:
    path: /products
    controller: App\Controller\ProductController::getProducts
    methods: GET
get_product:
  path: /products/{id}
  controller: App\Controller\ProductController::getProduct
  methods: GET

add_to_cart:
  path: /add_product/{id}
  controller: App\Controller\OrderController::addProduct
  methods: POST

remove_from_cart:
  path: /remove_product/{id}
  controller: App\Controller\OrderController::removeProduct
  methods: POST


get_cart:
  path: /cart
  controller: App\Controller\OrderController::getCart
  methods: GET


checkout:
  path: /checkout
  controller: App\Controller\OrderController::checkout
  methods: POST

registration:
  path: user/registration
  controller: App\Controller\UserController::registration
  methods: POST

get_current_user:
  path: user/me
  controller: App\Controller\UserController::getCurrentUser
  methods: GET

login:
  path: /login
  controller: App\Controller\UserController::login
  methods: POST


get_user_orders:
  path: user/orders
  controller: App\Controller\UserController::getUserOrders
  methods: GET


